apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: nodeport
  nodeport_port: 30080
  admin_user: admin
  postgres_storage_requirements:
    requests:
      storage: 8Gi
  projects_storage_size: 5Gi
